### ISSUE TITLE
Adding support for automagically detecting the pixoo device(s) on the same LAN

### ISSUE THREAD

**Issue by SomethingWithComputers** [SomethingWithComputers/pixoo#11]
Now that this `https://app.divoom-gz.com/Device/ReturnSameLANDevice` exists, we should be able to take advantage of it.

**Comment by Pfleiderer-Adrian** [comment]
Hi,
check out my fork/pull request:
https://github.com/SomethingWithComputers/pixoo/pull/13

**Comment by SomethingWithComputers** [comment]
Finally done and implemented :). Just create a `Pixoo()` object with an empty constructor or use `None` for the IP address
