### ISSUE TITLE
[FR] Automatic device discovery based on DeviceID/DeviceMAC

### ISSUE THREAD

**Issue by fonix232** [SomethingWithComputers/pixoo#12]
I'm considering writing a Home Assistant wrapper for this library at the moment. One of the harder challenges to do is the "wandering IP" - without setting up a fixed IP address (for which I'd need to use my router, as the Divoom app and API do not support any such network settings), when the device reconnects, it will get a new IP via DHCP.

This means that a HA integration instance cannot be based on the IP address alone.

For this purpose it would be great if the library offered a way to resolve a `Pixoo` class instance by supplying the DeviceID/DeviceMAC (which does not change), and using the `https://app.divoom-gz.com/Device/ReturnSameLANDevice` endpoint to get the actual IP address.

**Comment by Pfleiderer-Adrian** [comment]
Hi,

check out my fork/pull request:
https://github.com/SomethingWithComputers/pixoo/pull/13

thanks for the information :)

**Comment by fonix232** [comment]
Looks good on first blink - although I'd probably move the address resolution logic to a completely separate method, as to simplify `__init__`.

You might also want to rename the `address` parameter to something more matching, since now it's become address/macaddress/deviceid in one. Maybe `connectionString`? Or something similar?

**Comment by Pfleiderer-Adrian** [comment]
Hi,
thank you for your feedback.
You are right, the __init__ function should be simplified.
You can check my new commit. There are also a new function: __get_url_from_connection_string
:)

**Comment by SomethingWithComputers** [comment]
With the refactored code, this is not currently super needed, but I will look into including something like this for the next release!
