### ISSUE TITLE
Simulator shows black screen on Macbook with M1 Max

### ISSUE THREAD

**Issue by vhartikainen** [SomethingWithComputers/pixoo#15]
Had an issue using the simulator on Macbook with M1 Max. I ran into stackoverflow with similar issues and a solution that worked in my case. Maybe update of README.md would be in order (https://stackoverflow.com/questions/73056296/tkinter-on-mac-shows-up-as-a-black-screen)

> Run the following commands
> 1. brew uninstall tcl-tk uninstall the old tk if you have it
> 2. pyenv uninstall 3.10.5 ...or whatever your current global Python version is
> 3.brew install tcl-tk grab a fresh install of tk
> 4. pyenv install 3.10.5 grab a fresh install of Python 3.10.5 (or whichever)
> 5. pyenv global 3.10.5 set your global Python version (matching the version you just installed above)
> 
> You need to install tk via homebrew before installing Python with pyenv because pyenv will automatically try to use whatever tk package it can find when it installs Python.
> 
> This will also work if you are using pyenv to upgrade from one version of Python to another.

**Comment by SomethingWithComputers** [comment]
I've included it in the documentation under [Known Bugs ](https://github.com/SomethingWithComputers/pixoo?tab=readme-ov-file#known-bugs)
