### ISSUE TITLE
Make Pixoo a python package

### ISSUE THREAD

**Issue by netmanchris** [SomethingWithComputers/pixoo#17]
@SomethingWithComputers I'd love to use your python library in a Home Assistant project, but AppDaemon requires python libraries to be available on PyPi.  It looks like https://github.com/SomethingWithComputers/pixoo/pull/10 should allow this to happen.  I've already got your library working to draw the album artwork off my Sonos speakers and to display it on my Divoom 64.  

Is there any update on @jcarranz97's pull request? Any chance you're going to post this package to PyPi?

thanks for the great work!

**Comment by SomethingWithComputers** [comment]
I'll merge it in! Real life has been taking some priority lately but I'm coming back to do a bunch of updates soon (tm) ^^. I'll accept this one now

**Comment by netmanchris** [comment]
That would be amazing!  Stretch goal would be to post to pypi as well!   Really appreciate it!  Totally get priorities of life. Focus where you need it!  :)

**Comment by gickowtf** [comment]
Hey guys, i had Write a second Font do you want a pull request of it? What is the Status for pypi??

**Comment by gickowtf** [comment]
@netmanchris 
> @SomethingWithComputers I'd love to use your python library in a Home Assistant project, but AppDaemon requires python libraries to be available on PyPi.  

How can i use this Library in Hass?!

**Comment by kongo09** [comment]
I'm looking to create a Python package out of this after integrating some of the PRs. However, I'm not sure of the licence as this repo doesn't state any. @SomethingWithComputers : can you please advise?

Also, If @SomethingWithComputers picks up the work, I'm more than happy to hand over the PyPi package as I don't want to maintain this going forward, provided things haven't diverged too much by then.

**Comment by kongo09** [comment]
I found the licence to be __BSD__ as mentioned in the `setup.py` file so I felt free to publish the library here:
https://pypi.org/project/pixoo/

**Comment by SomethingWithComputers** [comment]
@kongo09 As I didn't add the setup.py, I wasn't aware somebody added the BSD license. I probably should've been more careful accepting pull requests perhaps. Though I don't really have a problem with this, I would very much prefer if pypi would refer to the original project (https://github.com/SomethingWithComputers/pixoo), instead of your fork. I have very strict coding standards and as a professor of computer science (with students that keep an eye on what I do), I don't want my name attached to code I didn't personally write or verify.

**Comment by kongo09** [comment]
I should probably remove your name then to keep it clean in terms of publishing the fork?

If I change the reference back to this repo, it will be inconsistent as I have continued to change a few things. However, if you would like to take over and publish yourself, that's also fine for me.

Is the BSD licence ok for you?

**Comment by KoenDierckx** [comment]
First off, thanks for your code @SomethingWithComputers 
I would also really like this to be an official PyPi package

Any plans to release this yourself, or is the fork from @kongo09 the way forward ?

**Comment by SomethingWithComputers** [comment]
@KoenDierckx thanks for the kind words! I was hoping the package's ownership would be transferred to me seeing that it is using the name of this repo and I prefer consistency- but it seems so far like they've taken ownership of the name but referring it to their own fork (with some code in there that doesn't necessarily follow the code conventions and seemingly breaks some of the consistencies I would prefer). 

So I'm inclined to say you can use it, but even though it uses this repo's name, it's not owned, verified, endorsed, or validated by me.

I'd rather not start a package with a name different than the repo, but I suppose that's the way forward now.

**Comment by SomethingWithComputers** [comment]
@kongo09 I would prefer it if you changed the name of your forks' python package to use something other than the official name (pixoo), so that to original with the updates I'm planning on pushing this week can be registered under its own name.

**Comment by kongo09** [comment]
As I said before, I don't want to create confusion. I have to admit I'm not sure what coding conventions you feel I violated. I didn't invent anything by followed the suggestions of `pylint`  which generated lots of warnings in your original code.

I did by now integrate a few additional things that I wouldn't want to lose, like
- automatically finding the first pixoo device in the network
- simplify API calls
- adding another font
- taking in some PRs of others

It felt some of the PRs in the original repo were sitting around for many months without much action, so I'm not entirely sure what the plan is? Are you going to actively maintain your repo and consider PRs or do you consider the code final?

Depending on what your plans are, we could
- simply transfer ownership (which would be the ideal case) or
- transfer ownership, but I publish a second version if you don't plan to upgrade your package

**Comment by SomethingWithComputers** [comment]
Transferring ownership would be fine but I'm not 100% sure how that would work, can it simply be transferred to my PyPI account (SomethingWithComputers) or is it based on email? In that case, ron@somethingwithcomputers.com.

I have some pretty major upgrades in the works that I'll start pushing out in phases in the coming weeks.

**Comment by KoenDierckx** [comment]
Could we do a PR back from @kongo09's fork, into this repo ?
Than we have the latest changes, including the config for the pypi package
Then @SomethingWithComputers can review that, and update if needed to his conventions
And after that a transfer of ownership for the pypi account should be trivial

**Comment by kongo09** [comment]
Transfer on pypi is easy. I've registered you as an owner. The moment you kick me out, it's all yours.

Let me know if you want a PR - or simply pull in the stuff yourself. I've renamed my repo to `pixoo-ng` and created a separate library here: https://pypi.org/project/pixoo-ng/

**Comment by KoenDierckx** [comment]
Hey @kongo09 I appreciate the quick response, and way how you handled things.
This seems like the best way to move forward for all within the spirit of the open source world

Now @SomethingWithComputers can take ownership of his library, both on github and pypi
And you can progress with your fork on your own pace 

I do hope that @SomethingWithComputers is open to integrate your extensions into his codebase, and finds the time to do so soon. As there are some very useful additions there.

So I hope to see new versions from both of your libraries in the near future on pypi 
Keep of the good work !

**Comment by SomethingWithComputers** [comment]
@kongo09 Now that I've finally moved to a new house and such, I'm working on a bunch of updates and integrations that I'd like to push- however I cannot modify the PyPI package because you're still the owner on PyPI.org - could you transfer ownership to me so that I can set it up correctly? I've not been registered as an owner, but as a maintainer.

**Comment by kongo09** [comment]
Oh, I was under the impression I did it correctly? Let me take another look...

**Comment by SomethingWithComputers** [comment]
@kongo09 no problem! Let me know if you need anything from me.

**Comment by SomethingWithComputers** [comment]
@kongo09 Did you have a chance to have a look? There are about a dozen upgrades I've pushed to the develop branch that I would like to release on PyPI (after some more testing is done)

**Comment by kongo09** [comment]
Can you check again, please?

**Comment by SomethingWithComputers** [comment]
> Can you check again, please?

It works now! Thank you, I've pushed the latest version with all new updates/upgrades :).
