### ISSUE TITLE
Initial setup via bluetooth

### ISSUE THREAD

**Issue by ghost** [SomethingWithComputers/pixoo#22]
Would it be possible to sniff the bluetooth packets and reverse engineer the initial setup of the Pixoo64 over bluetooth, so that the Divoom app is no longer needed?

https://hackaday.com/2021/03/23/a-crash-course-on-sniffing-bluetooth-low-energy/

Thank you.

**Comment by SomethingWithComputers** [comment]
I suppose it might be possible, but it'll be very difficult to get work on different architectures. For example I use a Raspberry pi to control my Divoom, some people use old windows laptops, some people use linux, some use macOS, all require different implementations of the bluetooth interface.

Reverse engineering something like that would take a very long time unless you can decompile the original app and find the protocols for the initial setup. And yet, it probably will not work on all systems.

Still, you're welcome to try!
